var supplements = [{
        id: 1,
        name: 'Чеддер',
        img: 'cheese/chedder.jpg',
        price: 20
    }, {
        id: 2,
        name: 'Фета',
        img: 'cheese/feta.jpg',
        price: 10
    }, {
        id: 3,
        name: 'Моцарела',
        img: 'cheese/mozzarella.png',
        price: 8
    }, {
        id: 4,
        name: 'Пармезан',
        img: 'cheese/parmesan.png',
        price: 5
    }, {
        id: 5,
        name: 'Бекон',
        img: 'meat/bacon.jpg',
        price: 10
    }, {
        id: 6,
        name: 'Курица',
        img: 'meat/chicken.jpg',
        price: 5
    }, {
        id: 7,
        name: 'Фрикадельки',
        img: 'meat/meatballs.png',
        price: 20
    }, {
        id: 8,
        name: 'Пеперони',
        img: 'meat/pepperoni.jpg',
        price: 15
    }, {
        id: 9,
        name: 'Ветчина',
        img: 'meat/vetchina.jpg',
        price: 10
    }, {
        id: 10,
        name: 'Лук',
        img: 'vegetables/bow.jpg',
        price: 5
    }, {
        id: 11,
        name: 'Грибы',
        img: 'vegetables/mushrooms.png',
        price: 5
    }, {
        id: 12,
        name: 'Оливки',
        img: 'vegetables/olives.jpg',
        price: 10
    }, {
        id: 13,
        name: 'Ананас',
        img: 'vegetables/pineapple.png',
        price: 20
    }, {
        id: 14,
        name: 'Помидоры',
        img: 'vegetables/Tomato.png',
        price: 15
    }],

    products = [{
        id: 1,
        name: "Пеперони",
        img: "pizza/peperoni.jpg",
        sizes: [{
            size: 'sm',
            price: 80
        }, {
            size: 'md',
            price: 120
        }, {
            size: 'xl',
            price: 180
        }]
    }, {
        id: 2,
        name: "Кантри",
        img: "pizza/cantry.jpg",
        sizes: [{
            size: 'sm',
            price: 120
        }, {
            size: 'md',
            price: 160
        }, {
            size: 'xl',
            price: 240
        }]
    }, {
        id: 3,
        name: "Техас",
        img: "pizza/texas.jpg",
        sizes: [{
            size: 'sm',
            price: 140
        }, {
            size: 'md',
            price: 190
        }, {
            size: 'xl',
            price: 280
        }]
    }, {
        id: 4,
        name: "Гавайская",
        img: "pizza/hawai.jpg",
        sizes: [{
            size: 'sm',
            price: 190
        }, {
            size: 'md',
            price: 250
        }, {
            size: 'xl',
            price: 280
        }]
    }, {
        id: 5,
        name: "Шпинат и Фета",
        img: "pizza/spinach-and-feta.png",
        sizes: [{
            size: 'sm',
            price: 90
        }, {
            size: 'md',
            price: 120
        }, {
            size: 'xl',
            price: 150
        }]
    }, {
        id: 6,
        name: "5 Сыров",
        img: "pizza/5cheeses.png",
        sizes: [{
            size: 'sm',
            price: 100
        }, {
            size: 'md',
            price: 130
        }, {
            size: 'xl',
            price: 160
        }]
    }, {
        id: 7,
        name: "Лосось филадельфия",
        img: "pizza/salmon.png",
        sizes: [{
            size: 'sm',
            price: 120
        }, {
            size: 'md',
            price: 160
        }, {
            size: 'xl',
            price: 210
        }]
    }, {
        id: 8,
        name: "Мюнхенская",
        img: "pizza/munich.png",
        sizes: [{
            size: 'sm',
            price: 130
        }, {
            size: 'md',
            price: 140
        }, {
            size: 'xl',
            price: 160
        }]
    }
    ];